In [116]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [117]:
df = pd.read_csv('ai_student_impact_dataset.csv')

In [118]:
df.shape

(50000, 16)

In [119]:
df.columns

Index(['Student_ID', 'Major_Category', 'Year_of_Study', 'Pre_Semester_GPA',
       'Weekly_GenAI_Hours', 'Primary_Use_Case', 'Prompt_Engineering_Skill',
       'Tool_Diversity', 'Paid_Subscription', 'Traditional_Study_Hours',
       'Perceived_AI_Dependency', 'Institutional_Policy',
       'Anxiety_Level_During_Exams', 'Post_Semester_GPA',
       'Skill_Retention_Score', 'Burnout_Risk_Level'],
      dtype='str')

In [120]:
subscription_mapping = {True: 1, False: 0}
df['Paid_Subscription'] = df['Paid_Subscription'].map(subscription_mapping)

In [121]:
df.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,1,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,0,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,0,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,0,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,0,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium

In [122]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  50000 non-null  int64
 1   Major_Category              50000 non-null  str
 2   Year_of_Study               50000 non-null  str
 3   Pre_Semester_GPA            50000 non-null  float64
 4   Weekly_GenAI_Hours          50000 non-null  float64
 5   Primary_Use_Case            50000 non-null  str
 6   Prompt_Engineering_Skill    50000 non-null  str
 7   Tool_Diversity              50000 non-null  int64
 8   Paid_Subscription           50000 non-null  int64
 9   Traditional_Study_Hours     50000 non-null  float64
 10  Perceived_AI_Dependency     50000 non-null  int64
 11  Institutional_Policy        50000 non-null  str
 12  Anxiety_Level_During_Exams  50000 non-null  int64
 13  Post_Semester_GPA           50000 non-null  float64
 14  Skill_Retention_Score       50000 non-null  float64
 15  Burnout_Risk_Level          50000 non-null  str
dtypes: float64(5), int64(5), str(6)
memory usage: 6.1 MB

In [123]:
df.isnull().sum()

Student_ID                    0
Major_Category                0
Year_of_Study                 0
Pre_Semester_GPA              0
Weekly_GenAI_Hours            0
Primary_Use_Case              0
Prompt_Engineering_Skill      0
Tool_Diversity                0
Paid_Subscription             0
Traditional_Study_Hours       0
Perceived_AI_Dependency       0
Institutional_Policy          0
Anxiety_Level_During_Exams    0
Post_Semester_GPA             0
Skill_Retention_Score         0
Burnout_Risk_Level            0
dtype: int64

In [124]:
df.describe()

,Student_ID,Pre_Semester_GPA,Weekly_GenAI_Hours,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score
count,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,125000.500000,3.146102,8.427752,2.80026,0.423080,11.209271,3.505360,4.270760,3.349299,75.798125
std,14433.901067,0.478854,8.269490,1.18802,0.494053,5.156426,1.820812,2.144066,0.495673,13.281626
min,100001.000000,1.183000,0.000000,1.00000,0.000000,1.000000,1.000000,1.000000,1.000000,10.780000
25%,112500.750000,2.834000,2.390000,2.00000,0.000000,7.560000,2.000000,3.000000,3.023750,66.820000
50%,125000.500000,3.210000,5.800000,3.00000,0.000000,11.180000,3.000000,4.000000,3.421000,76.000000
75%,137500.250000,3.521000,11.720000,4.00000,1.000000,14.710000,5.000000,6.000000,3.749000,85.190000
max,150000.000000,3.998000,40.000000,5.00000,1.000000,35.860000,10.000000,10.000000,4.000000,100.000000

In [125]:
## Which Major Category has the highest number of students?

category_with_highest_students = df['Major_Category'].value_counts().idxmax()
category_with_highest_students

'STEM'

In [126]:
df['Major_Category'].value_counts()

Major_Category
STEM          15059
Business      12538
Humanities     9994
Medical        6476
Arts           5933
Name: count, dtype: int64

In [127]:
## Which Year of Study uses GenAI the most?

year_of_study_with_highest_genai_usage = df.groupby('Year_of_Study')['Weekly_GenAI_Hours'].sum().idxmax()
print(year_of_study_with_highest_genai_usage)

year_of_study_with_lowest_genai_usage = df.groupby('Year_of_Study')['Weekly_GenAI_Hours'].sum().idxmin()
print(year_of_study_with_lowest_genai_usage)

Freshman
Graduate

In [128]:
df.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,1,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,0,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,0,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,0,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,0,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium

In [129]:
## Which year (Freshman, Sophomore, Junior, Senior) has the highest GPA improvement? GPA improvement = Final GPA - Initial GPA

df['GPA_Improvement'] = df['Post_Semester_GPA'] - df['Pre_Semester_GPA']

year_with_highest_gpa_improvement = df.groupby('Year_of_Study')['GPA_Improvement'].mean().idxmax()
print(year_with_highest_gpa_improvement)

Graduate

In [130]:
## How many hours per week does the average student spend using GenAI?

average_genai_hours = df.groupby('Year_of_Study')['Weekly_GenAI_Hours'].mean().groupby('Year_of_Study').mean()
print(average_genai_hours)

Year_of_Study
Freshman     8.446962
Graduate     8.406052
Junior       8.376325
Senior       8.459251
Sophomore    8.446249
Name: Weekly_GenAI_Hours, dtype: float64

In [131]:
## Which Primary Use Case is the most common?

most_common_use_case = df['Primary_Use_Case'].value_counts().idxmax()
print(most_common_use_case)

Debugging/Troubleshooting

In [132]:
## Which use case is associated with the largest GPA improvement?

use_case_with_largest_gpa_improvement = df.groupby('Primary_Use_Case')['GPA_Improvement'].mean().idxmax()
print(use_case_with_largest_gpa_improvement)

Debugging/Troubleshooting

In [133]:
## Does spending more hours with GenAI generally improve GPA?

correlation = df['Weekly_GenAI_Hours'].corr(df['GPA_Improvement'])
print(f"Correlation between Weekly GenAI Hours and GPA Improvement: {correlation}")

Correlation between Weekly GenAI Hours and GPA Improvement: -0.046479283140597336

In [134]:
## Which students improved the most this semester?

top_improvers = df.nlargest(5, 'GPA_Improvement')
top_improvers

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level,GPA_Improvement
11235,111236,Business,Sophomore,2.591,2.78,Debugging/Troubleshooting,Advanced,4,0,21.33,4,Allowed_With_Citation,4,3.599,93.20,Medium,1.008
8124,108125,STEM,Freshman,2.941,7.31,Debugging/Troubleshooting,Advanced,3,0,12.03,4,Strict_Ban,1,3.926,87.56,Low,0.985
2059,102060,Business,Junior,2.268,7.72,Debugging/Troubleshooting,Advanced,3,1,25.80,5,Strict_Ban,6,3.208,100.00,Medium,0.940
28332,128333,Business,Sophomore,3.025,9.29,Debugging/Troubleshooting,Advanced,4,0,17.76,5,Actively_Encouraged,1,3.955,100.00,Low,0.930
9580,109581,STEM,Senior,3.023,11.53,Debugging/Troubleshooting,Advanced,4,1,14.13,4,Allowed_With_Citation,4,3.943,83.87,High,0.920

In [137]:
## Are students paying for AI actually getting better results?

paid_students = df[df['Paid_Subscription'] == 1]
unpaid_students = df[df['Paid_Subscription'] == 0]

print(f"Average GPA Improvement for Paid Students: {paid_students['GPA_Improvement'].mean()}")
print(f"Average GPA Improvement for Unpaid Students: {unpaid_students['GPA_Improvement'].mean()}")

Average GPA Improvement for Paid Students: 0.20697102202893067
Average GPA Improvement for Unpaid Students: 0.200429487623934

In [141]:
## Who is becoming most dependent on AI? Analyze student by: Major, Year, Prompt Skill, Use Case

more_dependent_major_category = df.groupby('Major_Category')['Weekly_GenAI_Hours'].mean().idxmax()
print(f"Major Category with highest average GenAI usage: {more_dependent_major_category}")

Major Category with highest average GenAI usage: STEM

In [142]:
## What factors seem to increase burnout? Investigate relationships with: Weekly_GenAI_Hours, Traditional_Study_Hours, Anxiety_Level_During_Exams

burnout_correlation_genai = df['Weekly_GenAI_Hours'].corr(df['Anxiety_Level_During_Exams'])
burnout_correlation_study = df['Traditional_Study_Hours'].corr(df['Anxiety_Level_During_Exams'])
print(f"Correlation between GenAI usage and burnout: {burnout_correlation_genai}")
print(f"Correlation between traditional study hours and burnout: {burnout_correlation_study}")

Correlation between GenAI usage and burnout: 0.26907967009961126
Correlation between traditional study hours and burnout: -0.040935376488071086