#### Your next practice exercise

##### **Using your cleaned dataset, try the following:**

- Convert the DataFrame to a NumPy array.
- Create X (all columns except original_price) and y (original_price only).
**Print:**
- X.shape
- y.shape

**Find the average:**
- RAM
- Storage
- Battery capacity
- Find the maximum and minimum original_price.
- Normalize the battery_capacity column using NumPy.

***These exercises will give you practical experience with the exact NumPy operations you'll repeatedly use in machine learning.***

In [47]:
import pandas as pd
import numpy as np

In [48]:
df = pd.read_csv("used_phone_price_prediction_cleaned.csv")
df.head(5)

,brand,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,camera_score,os_type,has_5g,original_price,...,screen_cracked,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,resale_price
0,0,2025,4,256,6.93,4130,100,0,1,147337,...,0,0,0,0,0,0,11,1,1,47891.46
1,1,2024,16,64,6.29,5558,67,0,1,75725,...,0,0,0,0,2,1,8,1,0,17663.21
2,2,2022,4,128,5.52,5945,67,1,1,134358,...,0,0,0,0,0,0,0,0,1,67268.20
3,3,2024,16,512,5.99,5767,57,0,1,96807,...,0,0,0,1,0,1,11,1,1,12626.26
4,3,2021,4,128,6.59,5336,44,0,1,74505,...,0,0,0,0,2,1,24,1,1,20662.25

In [49]:
df.shape

(1000000, 25)

In [50]:
new_df = df.to_numpy()
new_df.shape

(1000000, 25)

In [51]:
new_df[0].shape

(25,)

In [52]:
new_df[9]

array([0.000000e+00, 2.022000e+03, 4.000000e+00, 1.280000e+02,
       6.100000e+00, 5.799000e+03, 7.200000e+01, 0.000000e+00,
       0.000000e+00, 9.620200e+04, 2.023000e+03, 7.000000e+01,
       3.100000e+00, 0.000000e+00, 7.400000e+01, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
       0.000000e+00, 7.000000e+00, 1.000000e+00, 1.000000e+00,
       1.991949e+04])

In [53]:
# - Create X (all columns except original_price) and y (original_price only).
# The index of the original_price column is 9

x = df.drop(columns=['original_price']).to_numpy()
y = df['original_price'].to_numpy()

In [54]:
x.shape

(1000000, 24)

In [55]:
y.shape

(1000000,)

In [56]:
# Taking the average of ram_gb column with numpy


avg_ram = np.mean(df['ram_gb'])
avg_ram

np.float64(9.201878)

In [57]:
# Taking the average of storage_gb column with pandas
avg_storage = df['storage_gb'].mean()
avg_storage

np.float64(396.798912)

In [58]:
# Taking the average of battery_capacity column with pandas

avg_battery = df['battery_capacity'].mean()
avg_battery

np.float64(4750.004425)

In [59]:
# Finding the minimum and maximum of original_price column with numpy

min_price = np.min(y)
max_price = np.max(y)
print(f"Minimum price: {min_price}, \nMaximum price: {max_price}")

Minimum price: 10000,
Maximum price: 150000

In [60]:
print(np.mean(y))

79966.195735

In [61]:
df.describe()

,brand,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,camera_score,os_type,has_5g,original_price,...,screen_cracked,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,resale_price
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.00000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,...,1000000.000000,1000000.000000,1000000.00000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,3.002193,2022.001836,9.201878,396.798912,6.25037,4750.004425,69.980058,0.142690,0.800063,79966.195735,...,0.079978,0.119653,0.15053,0.030106,0.999116,0.499737,8.099701,0.699651,0.849771,22597.996211
std,1.999934,2.001558,4.309755,349.401760,0.43290,1009.971322,17.607651,0.349757,0.399953,40413.479880,...,0.271259,0.324555,0.35759,0.170879,0.816232,0.500000,8.158009,0.458410,0.357296,16652.621181
min,0.000000,2019.000000,4.000000,64.000000,5.50000,3000.000000,40.000000,0.000000,0.000000,10000.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2000.000000
25%,1.000000,2020.000000,6.000000,128.000000,5.88000,3877.000000,55.000000,0.000000,1.000000,45028.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,10365.927500
50%,3.000000,2022.000000,8.000000,256.000000,6.25000,4750.000000,70.000000,0.000000,1.000000,79947.000000,...,0.000000,0.000000,0.00000,0.000000,1.000000,0.000000,6.000000,1.000000,1.000000,18555.195000
75%,5.000000,2024.000000,12.000000,512.000000,6.63000,5623.000000,85.000000,0.000000,1.000000,114984.000000,...,0.000000,0.000000,0.00000,0.000000,2.000000,1.000000,15.000000,1.000000,1.000000,30427.912500
max,6.000000,2025.000000,16.000000,1024.000000,7.00000,6500.000000,100.000000,1.000000,1.000000,150000.000000,...,1.000000,1.000000,1.00000,1.000000,2.000000,1.000000,24.000000,1.000000,1.000000,160257.480000

In [62]:
# Normalize the battery_capacity column using numpy 

df['battery_capacity_normalized'] = (df['battery_capacity'] - np.mean(df['battery_capacity'])) / np.std(df['battery_capacity'])
df['battery_capacity_normalized']

0        -0.613884
1         0.800019
2         1.183198
3         1.006955
4         0.580210
            ...
999995    1.592121
999996    1.378253
999997    1.112899
999998    0.465356
999999    1.696084
Name: battery_capacity_normalized, Length: 1000000, dtype: float64

In [63]:
x = x + df['battery_capacity_normalized'].to_numpy().reshape(-1, 1)
x.shape

(1000000, 24)

In [64]:
total_sales = np.sum(y)
total_sales

np.int64(79966195735)