### **Learn to create Series, DataFrames, and set up your environment**

In [4]:
## Creating Series
import pandas as pd
# Series = 1D Array
series = pd.Series([1, 2, 3, 4, 5])
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
import pandas as pd
import numpy as np

# Create a simple sales dataset
data = {
    'Transaction_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110], 
    'Date': ['2026-07-01', '2026-07-01', '2026-07-02', '2026-07-02', '2026-07-03', 
             '2026-07-03', '2026-07-04', '2026-07-04', '2026-07-05', '2026-07-05'],
    'Product': ['Laptop', 'Mouse', 'Monitor', 'Laptop', 'Mouse', 
                'Keyboard', 'Monitor', 'Laptop', 'Mouse', np.nan], # np.nan introduces a missing value for practice
    'Category': ['Electronics', 'Accessories', 'Electronics', 'Electronics', 'Accessories', 
                 'Accessories', 'Electronics', 'Electronics', 'Accessories', 'Accessories'],
    'Units_Sold': [1, 4, 2, 1, 5, 2, np.nan, 3, 10, 1], # nan for data cleaning practice
    'Unit_Price': [1200, 25, 300, 1200, 25, 50, 300, 1200, 25, 45],
    'Region': ['North', 'East', 'West', 'South', 'East', 'North', 'West', 'North', 'South', 'East']
}

## Creating the DataFrame from the dictionary
df = pd.DataFrame(data)
print(df)

   Transaction_ID        Date   Product     Category  Units_Sold  Unit_Price  \
0             101  2026-07-01    Laptop  Electronics         1.0        1200
1             102  2026-07-01     Mouse  Accessories         4.0          25
2             103  2026-07-02   Monitor  Electronics         2.0         300
3             104  2026-07-02    Laptop  Electronics         1.0        1200
4             105  2026-07-03     Mouse  Accessories         5.0          25
5             106  2026-07-03  Keyboard  Accessories         2.0          50
6             107  2026-07-04   Monitor  Electronics         NaN         300
7             108  2026-07-04    Laptop  Electronics         3.0        1200
8             109  2026-07-05     Mouse  Accessories        10.0          25
9             110  2026-07-05       NaN  Accessories         1.0          45

  Region
0  North
1   East
2   West
3  South
4   East
5  North
6   West
7  North
8  South
9   East

In [5]:
df.head(5)  # Display the first 5 rows of the DataFrame

,Transaction_ID,Date,Product,Category,Units_Sold,Unit_Price,Region
0,101,2026-07-01,Laptop,Electronics,1.0,1200,North
1,102,2026-07-01,Mouse,Accessories,4.0,25,East
2,103,2026-07-02,Monitor,Electronics,2.0,300,West
3,104,2026-07-02,Laptop,Electronics,1.0,1200,South
4,105,2026-07-03,Mouse,Accessories,5.0,25,East

In [ ]:
df.info() # Display information about the DataFrame, including data types and non-null counts

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  10 non-null     int64
 1   Date            10 non-null     str
 2   Product         9 non-null      str
 3   Category        10 non-null     str
 4   Units_Sold      9 non-null      float64
 5   Unit_Price      10 non-null     int64
 6   Region          10 non-null     str
dtypes: float64(1), int64(2), str(4)
memory usage: 692.0 bytes

In [ ]:
df.describe() # Display summary statistics for numerical columns in the DataFrame

       Transaction_ID  Units_Sold  Unit_Price
count        10.00000    9.000000    10.00000
mean        105.50000    3.222222   437.00000
std           3.02765    2.905933   537.14368
min         101.00000    1.000000    25.00000
25%         103.25000    1.000000    30.00000
50%         105.50000    2.000000   175.00000
75%         107.75000    4.000000   975.00000
max         110.00000   10.000000  1200.00000

In [8]:
df["Category"].unique()  # Display unique values in the 'Category' column

<StringArray>
['Electronics', 'Accessories']
Length: 2, dtype: str

In [ ]:
df.shape # Display the shape of the DataFrame (rows, columns)

(10, 7)

In [12]:
for col in df.columns:
    print(f"Column: {col}, Unique Values: {df[col].nunique()}")  # Display the number of unique values in each column

Column: Transaction_ID, Unique Values: 10
Column: Date, Unique Values: 5
Column: Product, Unique Values: 4
Column: Category, Unique Values: 2
Column: Units_Sold, Unique Values: 6
Column: Unit_Price, Unique Values: 5
Column: Region, Unique Values: 4

In [13]:
df.isnull().sum()  # Count the number of missing values in each column

Transaction_ID    0
Date              0
Product           1
Category          0
Units_Sold        1
Unit_Price        0
Region            0
dtype: int64

In [17]:
# Printing the null value of Product colunm

df[df['Product'].isnull()]  # Display rows where 'Product' is null

,Transaction_ID,Date,Product,Category,Units_Sold,Unit_Price,Region
9,110,2026-07-05,NaN,Accessories,1.0,45,East

In [23]:
# Filling Null values

df["Product"] = df["Product"].fillna("Unknown", inplace=True)  # Fill null values in the 'Product' column with "Unknown"
print("Missing values in 'Product' column:", df["Product"].isnull().sum())  # Verify that there are no more null values in the 'Product' column
print("\n\n", df["Product"])

Missing values in 'Product' column: 0


 0      Laptop
1       Mouse
2     Monitor
3      Laptop
4       Mouse
5    Keyboard
6     Monitor
7      Laptop
8       Mouse
9     Unknown
Name: Product, dtype: str

C:\Users\imher\AppData\Local\Temp\ipykernel_7792\2138641407.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Product"] = df["Product"].fillna("Unknown", inplace=True)  # Fill null values in the 'Product' column with "Unknown"

In [25]:
df.to_csv("sales_data.csv", index=False)  # Save the DataFrame to a CSV file without the index