In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("business_sales.csv")
df.head(5)

,Customer_ID,Age,Gender,City,Monthly_Income,Orders,Average_Order_Value,Discount_Used,Returned_Items,Satisfaction,Subscription
0,1001,22,Male,Karachi,45000,12,1800,Yes,1,4,No
1,1002,31,Female,Lahore,72000,20,2500,No,0,5,Yes
2,1003,27,Male,Islamabad,55000,15,2100,Yes,2,3,No
3,1004,45,Female,Karachi,98000,30,3200,No,1,5,Yes
4,1005,35,Male,Peshawar,68000,18,2400,Yes,0,4,Yes

In [5]:
df.shape

(20, 11)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Customer_ID          20 non-null     int64
 1   Age                  20 non-null     int64
 2   Gender               20 non-null     str
 3   City                 20 non-null     str
 4   Monthly_Income       20 non-null     int64
 5   Orders               20 non-null     int64
 6   Average_Order_Value  20 non-null     int64
 7   Discount_Used        20 non-null     str
 8   Returned_Items       20 non-null     int64
 9   Satisfaction         20 non-null     int64
 10  Subscription         20 non-null     str
dtypes: int64(7), str(4)
memory usage: 1.8 KB

In [4]:
df.describe()

,Customer_ID,Age,Monthly_Income,Orders,Average_Order_Value,Returned_Items,Satisfaction
count,20.00000,20.000000,20.000000,20.000000,20.000000,20.00000,20.000000
mean,1010.50000,33.550000,68900.000000,19.350000,2450.000000,0.90000,3.900000
std,5.91608,7.735598,19678.735518,7.227688,581.287138,0.91191,1.020836
min,1001.00000,22.000000,43000.000000,9.000000,1600.000000,0.00000,2.000000
25%,1005.75000,27.750000,52500.000000,13.750000,1975.000000,0.00000,3.000000
50%,1010.50000,32.500000,66500.000000,18.500000,2375.000000,1.00000,4.000000
75%,1015.25000,39.250000,83750.000000,24.500000,2962.500000,1.25000,5.000000
max,1020.00000,50.000000,110000.000000,35.000000,3600.000000,3.00000,5.000000

In [6]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'City', 'Monthly_Income', 'Orders',
       'Average_Order_Value', 'Discount_Used', 'Returned_Items',
       'Satisfaction', 'Subscription'],
      dtype='str')

In [7]:
str_colunms = df.select_dtypes(include='object').columns
str_colunms

C:\Users\imher\AppData\Local\Temp\ipykernel_11556\1517683662.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  str_colunms = df.select_dtypes(include='object').columns

Index(['Gender', 'City', 'Discount_Used', 'Subscription'], dtype='str')

In [8]:
df["Gender"].value_counts()

Gender
Male      10
Female    10
Name: count, dtype: int64

In [9]:
df["Discount_Used"].value_counts()

Discount_Used
No     11
Yes     9
Name: count, dtype: int64

In [10]:
df["Subscription"].value_counts()

Subscription
Yes    12
No      8
Name: count, dtype: int64

In [11]:
df["City"].value_counts()

City
Karachi       7
Lahore        4
Islamabad     3
Peshawar      2
Quetta        1
Multan        1
Hyderabad     1
Faisalabad    1
Name: count, dtype: int64

In [12]:
df["Gender"] = df["Gender"].map({"Male":0,"Female":1})
df["Discount_Used"] = df["Discount_Used"].map({"No":0,"Yes":1})
df["Subscription"] = df["Subscription"].map({"No":0,"Yes":1})

city_mapping = {
    city:i
    for i,city in enumerate(df["City"].unique())
}

df["City"] = df["City"].map(city_mapping)

df.head(5)

,Customer_ID,Age,Gender,City,Monthly_Income,Orders,Average_Order_Value,Discount_Used,Returned_Items,Satisfaction,Subscription
0,1001,22,0,0,45000,12,1800,1,1,4,0
1,1002,31,1,1,72000,20,2500,0,0,5,1
2,1003,27,0,2,55000,15,2100,1,2,3,0
3,1004,45,1,0,98000,30,3200,0,1,5,1
4,1005,35,0,3,68000,18,2400,1,0,4,1

In [13]:
# Exporting the cleaned data to a new CSV file
df.to_csv("cleaned_business_sales.csv", index=False)